# Numpy - presentation

## Avis de Licence Originale

Ce notebook est principalement extrait du cours CS231.
Il a été adapté à cet Objectif de Formation.
Licence: MIT

Source originale: https://github.com/cs231n/cs231n.github.io/blob/master/python-colab.ipynb

This tutorial was originally written by Justin Johnson for cs231n. It was adapted as a Jupyter notebook for cs228 by Volodymyr Kuleshov and Isaac Caswell.

This version has been adapted for Colab by Kevin Zakka for the Spring 2020 edition of cs231n. It runs Python3 by default.

## Numpy

Numpy est la bibliotèque de base du calcul scientifique dans python. Il fournit un objet <code>array</code> multidimensionelle de haute performance et des outils pour travailler avec celles-ci.

Si vous connaissez déjà Matlab, vous pouvez trouver ce [Tutoriel] (https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) utile pour commencer avec numpy.

In [1]:
# np is the usual alias for numpy
import numpy as np

## np.array

Une numpy <code>array</code> ou tableau est un ensemble de valeurs, toutes du même type, et est indexé par un tuple d'entiers (un entier pour chaque dimension)
Le nombre de dimensions est le rang de l'array.
La <code>shape</code> d'une array est un tuple d'entrées donnant la taille de l'<code>array</code> le long de chaque dimension.

Nous pouvons initialiser les tableaux numpy à partir de listes python imbriquées et accéder aux éléments à l'aide de crochets (square brackets):

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [2]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy fournit également de nombreuses fonctions pour créer des tableaux

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

Le tableau précédent peut également être créé avec <code>np.ones</code> (pour les personnes qui n'aiment pas se souvenir des noms de fonction)

In [4]:
np.ones((2, 2)) * 7

array([[7., 7.],
       [7., 7.]])

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


Comme vous pouvez le voir, tous les tableaux précédents sont de type <code>float</code>, mais vous pouvez utiliser les mêmes fonctions en spécifiant le type

In [ ]:
np.ones((2, 2), dtype=np.int32)

Hey ! Pourquoi définissons-nous le type ? Je pensais que python était typé dynamiquant.
Oui, mais numpy ne l'est pas. Numpy est un emballage Python sur des structures C++, ils sont donc typés statiquement.

On peut également créer des valeurs aléatoires (par défaut des float entre 0 et 1)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.8690054  0.57244319]
 [0.29647245 0.81464494]]


### Indexation du Tableau

Numpy offre plusieurs façons d'indexer les tableaux.

De la même façon que les listes de python, on peut utiliser la range selection sur les tableaux numpy. Etant Donné que les tableaux peuvent être multidimensionnels, vous devez spécifier un range pour chaque dimension du tableau

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


Une "range selection" d'un tableau est une vue sur les mêmes données, donc la modification des données modifie le tableau d'origine.

Cela évite des copies de données coûteuses en mémoire et en temps de calcul

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


Vous pouvez également mélanger l'indexation par entier avec l'indexation par range. Cela donne un tableau de rang inférieur que le tableau d'origine. 

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Indexation du Tableau Enther: Lorsque Vous Indexez dans les tableaux numpy en utilisant le TRANCHAGE, La vue du Tableau Résultant Sera Toujours un Sous-Réseau du Tableau d'Origine. En Revanche, L'indexation du Tableau Enther Vous Permet de Construire des Tableaux Arbitraires à L'identité des Donnés d'Unt Tableau. Voici un exemple:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


On peut également utiliser une liste d'index

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Indexation booléenne du tableau

L'indexation booleenne du tableau vous permet de choisir des éléments arbitraires d'un tableau. Souvent, ce type d'indexation est utilisée pour selectionner les éléments d'un tableau qui satisfait une condition. Voici un exemple:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


### Types de Donnés

Chaque tableau numpy est une collection d'éléments du même type. Numpy fournit un grand nombre de types de données numériques que vous pouvez utiliser pour construire des tableaux. Numpy essaie de deviner un type de donnée lorsque vous créez un tableau sans le spécifier explicetement, mais il peut être spécifié explicitement. Voici un exemple:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Vous pouvez-tout lire sur les donnés numpy dans La [Documentation] (http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Opérations mathématiques

Les fonctions mathématiques de base fonctionnent par  élément sur les tableaux et sont disponibles à la foi en tant que surcharges d'opérateur et de fonctions dans le module:

In [6]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


Quel est l'utilité d'avoir la fonction <code>np.add</code> ? Dans la plupart des cas, vous n'en avez pas besoin, mais np.add est plus facile à référencer. Comparer :

In [10]:
from functools import reduce

print(reduce(np.add, [x,x,x]))
# and
print(reduce(lambda x, y: x + y, [x,x,x]))

[[ 3.  6.]
 [ 9. 12.]]
[[ 3.  6.]
 [ 9. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Notez que contrairement à matlab, '\*' est une multiplication par élément, pas une multiplication matricielle. Nous utiliserons plutôt la fonction <code>dot</code> pour calculer les produits de vecteurs, et / ou de matrice.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


Vous pouvez également utiliser l'opérateur `@` qui est équivalent.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy fournit de nombreuses fonctions utiles, par exemple la somme <code>np.sum</code>

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Vous pouvez trouver la liste complete des fonctions mathématiques fournies par numpy dans la [Documentation] (http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Outre le calcul des fonctions mathématiques à l'identité de tableaux, les devons nous souvent remodeler ou manipuler des données dans les tableaux. L'EXEMPLE LE PLUS SIMPLE DE CE TYPE D'OPÉRATION COSE À TRANSPOSER MATRICE UNE; Verser le transposeur UNE Matrice, Utilisez Simplement L'attribute t D'UN OBJET DE TABLEAU:

In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


### Le "broadcasting"

La diffusion est un mécanisme PUISSANT QUI PERMET à Numpy de Fonctionner Avec des Tableaux de DiFférentes formes lors de l'Exécution d'Opérations arithmétiques. Souvent, nous avons un réeuse plus Petit et un Tableau plus Grand, et nous Voulons Utiliser le RÉASEAL Plus Petit Plusieurs fois pour effeter un péu de fonctionnelment Sur le RÉESEAU plus Grand.

Par exemple, supposons que les chouilles aJouter un vecteur constant à chaque ligne d'uni matrice. Les pourrions le faire comme ceci:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Cela Marche; Cependant, Lorsque la Matrice `X` EST TRÈS GRAND, LE CALCUL D'UNE BOUCLE DANS Python Python pourrAIT ÊTRE Lent. Remarque que l'ajout du vecteur v à chaque ligne de la matrice `x` équivaut à l'ancien une matrice` vv` en empilant les copions de` v` vertical, puis effectuant une sommation élémentaire de` x` et `vv`. Les pourrions mettre en œvre cette approche comme ceci:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy Broadcasting wous Permet d'effetuer ce calcul Sans Creer plusieurs copies de v. Version de cille consideur, en utilisant la diffusion:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


La ligne `y = x + v` fonctionne même si` x` a la forme` (4, 3) `et` v` a une forme` (3,) `en raison de la diffusion; CETT LIGNE fonctionne Comme si V AVAIT RÉELLENT LA FORME «(4, 3)», Où chaque ligne était une copie de «v», et la somme a été EffetUee élémentaire.

La diffusion de deux Tableaux Ensemble CES RÈGLES:

1. Si les Tableaux n'ont pas le Même Rang, ajoutez la forme du réseau de rang infrérieur avec 1 jusqu'à ce que les deux formes aiging la même longueur.
2. Les deux compatibles sérèles de tableaux dans la dimension un de dimension s'ils aT la Même Taille dans la dimension, ou si l'u des tableaux une dimension de cette dans la tiille 1 dans.
3. Les Tableaux peuvent Être Diffusés Ensemble s'ils SONT compatibles dans les toutes les dimensions.
4. APPRÈS LA DIFFUSION, CHAQUE Tableau se comporte comme'il AVAIT UNE FORME ÉGALE AU MAXIMUM ÉLÉMENTAIRE DE FORMES DES DEUX Tableaux d'Entrée.
5. Dans n'importe quelle dimension où un tableau avait la tille 1 et l'autre tableau avait une taille supérieure à 1, le premier tableau se comporte comme s'il était copié le long de cette dimension

Si CETTe Explication N'a Pas de Sens, Essayez de Lire L'Explication de la [Documentation] (http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) ou CETT [Explication] (Explication] ( http: // wiki.scipy.org/ericsbroadcastingdoc).

Les Fonctions qui préventent la charge la diffusion SONT Appelaes Fonctions Universelles. Vous Pouvez Trouver la Liste de Toutes les Fonctions Universelles dans La [Documentation] (http://docs.scipy.org/doc/numpy/reference/ufuns.html#available-ufuncs).

Applications voici quelles de la diffusion:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


La Diffusion Rend Généralement Votre Code plus Concis et plus Rapide, Vous Devez Donc Vous Efforcer de L'utiliser dans la Mesure du possible.

Ce Bref Aperçu a Abordé Bon Nombre des Chose Importède que Vous Devez Savoir Sur Numpy, Line d'est d'est complété. CONSULTREZ LA [NUmpy Reference] (http://docs.scipy.org/doc/numpy/reference/) verse en savoir plus Sur Numpy.