$$
\def\CC{\bf C}
\def\QQ{\bf Q}
\def\RR{\bf R}
\def\ZZ{\bf Z}
\def\NN{\bf N}
$$
# Scipy : high-level scientific computing

**Authors**: *Gaël Varoquaux, Adrien Chauve, Andre Espaze, Emmanuelle
Gouillart, Ralf Gommers*

**Scipy**

The `scipy` package contains various toolboxes dedicated to common
issues in scientific computing. Its different submodules correspond to
different applications, such as interpolation, integration,
optimization, image processing, statistics, special functions, etc.

Tip

`scipy` can be compared to other standard scientific-computing
libraries, such as the GSL (GNU Scientific Library for C and C++), or
Matlab's toolboxes. `scipy` is the core package for scientific routines
in Python; it is meant to operate efficiently on `numpy` arrays, so that
numpy and scipy work hand in hand.

Before implementing a routine, it is worth checking if the desired data
processing is not already implemented in Scipy. As non-professional
programmers, scientists often tend to **re-invent the wheel**, which
leads to buggy, non-optimal, difficult-to-share and unmaintainable code.
By contrast, `Scipy`'s routines are optimized and tested, and should
therefore be used when possible.

Chapters contents

Warning

This tutorial is far from an introduction to numerical computing. As
enumerating the different submodules and functions in scipy would be
very boring, we concentrate instead on a few examples to give a general
idea of how to use `scipy` for scientific computing.

`scipy` is composed of task-specific sub-modules:

<table>
<tbody>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.cluster</code></td>
<td><blockquote>
<p>Vector quantization / Kmeans</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.constants</code></td>
<td><blockquote>
<p>Physical and mathematical constants</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.fftpack</code></td>
<td><blockquote>
<p>Fourier transform</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.integrate</code></td>
<td><blockquote>
<p>Integration routines</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.interpolate</code></td>
<td><blockquote>
<p>Interpolation</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.io</code></td>
<td><blockquote>
<p>Data input and output</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.linalg</code></td>
<td><blockquote>
<p>Linear algebra routines</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.ndimage</code></td>
<td><blockquote>
<p>n-dimensional image package</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.odr</code></td>
<td><blockquote>
<p>Orthogonal distance regression</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.optimize</code></td>
<td><blockquote>
<p>Optimization</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.signal</code></td>
<td><blockquote>
<p>Signal processing</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.sparse</code></td>
<td><blockquote>
<p>Sparse matrices</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.spatial</code></td>
<td><blockquote>
<p>Spatial data structures and algorithms</p>
</blockquote></td>
</tr>
<tr class="even">
<td><code class="interpreted-text" data-role="mod">scipy.special</code></td>
<td><blockquote>
<p>Any special mathematical functions</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><code class="interpreted-text" data-role="mod">scipy.stats</code></td>
<td><blockquote>
<p>Statistics</p>
</blockquote></td>
</tr>
</tbody>
</table>

Tip

They all depend on `numpy`, but are mostly independent of each other.
The standard way of importing Numpy and these Scipy modules is:

In [ ]:
import numpy as np
import scipy as sp

## File input/output: `scipy.io`

**Matlab files**: Loading and saving:

In [ ]:
import scipy as sp
a = np.ones((3, 3))
sp.io.savemat('file.mat', {'a': a}) # savemat expects a dictionary
data = sp.io.loadmat('file.mat')
data['a']

array([[1.,  1.,  1.],
       [1.,  1.,  1.],
       [1.,  1.,  1.]])

Warning

**Python / Matlab mismatches**, *eg* matlab does not represent 1D arrays

In [ ]:
a = np.ones(3)
a

array([1.,  1.,  1.])

In [ ]:
sp.io.savemat('file.mat', {'a': a})
sp.io.loadmat('file.mat')['a']

array([[1.,  1.,  1.]])

Notice the difference?

**Image files**: Reading images:

In [ ]:
import imageio.v3 as iio
iio.imread('fname.png')

array([[[ 0,   0,  0, 255]]], dtype=uint8)

In [ ]:
# Matplotlib also has a similar function
import matplotlib.pyplot as plt
plt.imread('fname.png')

array([[[0., 0., 0., 1.]]], dtype=float32)

-   Load text files: `numpy.loadtxt`/`numpy.savetxt`
-   Clever loading of text/csv files:
    `numpy.genfromtxt`/`numpy.recfromcsv`
-   Fast and efficient, but numpy-specific, binary format:
    `numpy.save`/`numpy.load`
-   More advanced input/output of images in scikit-image: `skimage.io`

## Special functions: `scipy.special`

Special functions are transcendental functions. The docstring of the
`scipy.special` module is well-written, so we won't list all functions
here. Frequently used ones are:

> -   Bessel function, such as `scipy.special.jn` (nth integer order
>     Bessel function)
> -   Elliptic function (`scipy.special.ellipj` for the Jacobian
>     elliptic function, ...)
> -   Gamma function: `scipy.special.gamma`, also note
>     `scipy.special.gammaln` which will give the log of Gamma to a
>     higher numerical precision.
> -   Erf, the area under a Gaussian curve: `scipy.special.erf`

## Linear algebra operations: `scipy.linalg`

Tip

The `scipy.linalg` module provides standard linear algebra operations,
relying on an underlying efficient implementation (BLAS, LAPACK).

-   The `scipy.linalg.det` function computes the determinant of a square
    matrix:

In [ ]:
    import scipy as sp
    arr = np.array([[1, 2],
                    [3, 4]])
    sp.linalg.det(arr)

-2.0

In [ ]:
    arr = np.array([[3, 2],
                    [6, 4]])
    sp.linalg.det(arr)

0.0

In [ ]:
    sp.linalg.det(np.ones((3, 4)))

Traceback (most recent call last):
...
ValueError: expected square matrix

-   The `scipy.linalg.inv` function computes the inverse of a square
    matrix:

In [ ]:
    arr = np.array([[1, 2],
                    [3, 4]])
    iarr = sp.linalg.inv(arr)
    iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
    np.allclose(arr @ iarr, np.eye(2))

True


    Finally computing the inverse of a singular matrix (its determinant
    is zero) will raise `LinAlgError` :
```{.python .input}
    arr = np.array([[3, 2],
                    [6, 4]])
    sp.linalg.inv(arr)  # doctest: +SKIP
```
```{.json .output}
    [{"data": {"text/plain": "Traceback (most recent call last):\n...\n...LinAlgError: singular matrix"}, "execution_count": 1, "metadata": {}, "output_type": "execute_result"}]
```


-   More advanced operations are available, for example singular-value
    decomposition (SVD):

In [ ]:
    arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])
    uarr, spec, vharr = sp.linalg.svd(arr)


    The resulting array spectrum is:
```{.python .input}
    spec    # doctest: +ELLIPSIS
```
```{.json .output}
    [{"data": {"text/plain": "array([14.88982544,   0.45294236,   0.29654967])"}, "execution_count": 1, "metadata": {}, "output_type": "execute_result"}]
```

    The original matrix can be re-composed by matrix multiplication of
    the outputs of `svd` with `@` :
```{.python .input}
    sarr = np.diag(spec)
    svd_mat = uarr @ sarr @ vharr
    np.allclose(svd_mat, arr)
```
```{.json .output}
    [{"data": {"text/plain": "True"}, "execution_count": 1, "metadata": {}, "output_type": "execute_result"}]
```

    SVD is commonly used in statistics and signal processing. Many other
    standard decompositions (QR, LU, Cholesky, Schur), as well as
    solvers for linear systems, are available in `scipy.linalg`.


## Interpolation: `scipy.interpolate`

`scipy.interpolate` is useful for fitting a function from experimental
data and thus evaluating points where no measure exists. The module is
based on the [FITPACK Fortran subroutines]().

By imagining experimental data close to a sine function:

In [ ]:
measured_time = np.linspace(0, 1, 10)
noise = (np.random.random(10)*2 - 1) * 1e-1
measures = np.sin(2 * np.pi * measured_time) + noise

`scipy.interpolate.interp1d` can build a linear interpolation function:

In [ ]:
linear_interp = sp.interpolate.interp1d(measured_time, measures)

[<img src="auto_examples/images/sphx_glr_plot_interpolation_001.png" alt="image" class="align-right" />](auto_examples/plot_interpolation.html)

Then the result can be evaluated at the time of interest:

In [ ]:
interpolation_time = np.linspace(0, 1, 50)
linear_results = linear_interp(interpolation_time)

A cubic interpolation can also be selected by providing the `kind`
optional keyword argument:

In [ ]:
cubic_interp = sp.interpolate.interp1d(measured_time, measures, kind='cubic')
cubic_results = cubic_interp(interpolation_time)

`scipy.interpolate.interp2d` is similar to `scipy.interpolate.interp1d`,
but for 2-D arrays. Note that for the $interp$ family, the interpolation
points must stay within the range of given data points. See the summary
exercise on
[summary\_exercise\_stat\_interp](summary_exercise_stat_interp.ipynb)
for a more advanced spline interpolation example.

## Optimization and fit: `scipy.optimize`

Optimization is the problem of finding a numerical solution to a
minimization or equality.

Tip

The `scipy.optimize` module provides algorithms for function
minimization (scalar or multi-dimensional), curve fitting and root
finding.

### Curve fitting

[<img src="auto_examples/images/sphx_glr_plot_curve_fit_001.png" alt="image" class="align-right" />](auto_examples/plot_curve_fit.html)

Suppose we have data on a sine wave, with some noise: :

In [ ]:
x_data = np.linspace(-5, 5, num=50)
y_data = 2.9 * np.sin(1.5 * x_data) + np.random.normal(size=50)

If we know that the data lies on a sine wave, but not the amplitudes or
the period, we can find those by least squares curve fitting. First we
have to define the test function to fit, here a sine with unknown
amplitude and period:

In [ ]:
def test_func(x, a, b):
    return a * np.sin(b * x)

[<img src="auto_examples/images/sphx_glr_plot_curve_fit_002.png" alt="image" class="align-right" />](auto_examples/plot_curve_fit.html)

We then use `scipy.optimize.curve_fit` to find $a$ and $b$ :

In [ ]:
params, params_covariance = sp.optimize.curve_fit(test_func, x_data, y_data, p0=[2, 2])
print(params)

[3.05931973  1.45754553]

<div style="clear: both"></div>

**Exercise: Curve fitting of temperature data**

The temperature extremes in Alaska for each month, starting in January,
are given by (in degrees Celcius):

In [ ]:
max:  17,  19,  21,  28,  33,  38, 37,  37,  31,  23,  19,  18
min: -62, -59, -56, -46, -32, -18, -9, -13, -25, -46, -52, -58

1.  Plot these temperature extremes.
2.  Define a function that can describe min and max temperatures. Hint:
    this function has to have a period of 1 year. Hint: include a time
    offset.
3.  Fit this function to the data with `scipy.optimize.curve_fit`.
4.  Plot the result. Is the fit reasonable? If not, why?
5.  Is the time offset for min and max temperatures the same within the
    fit accuracy?

`solution <sphx_glr_intro_scipy_auto_examples_solutions_plot_curvefit_temperature_data.py>`

### Finding the minimum of a scalar function

[<img src="auto_examples/images/sphx_glr_plot_optimize_example1_001.png" alt="image" class="align-right" />](auto_examples/plot_optimize_example1.html)

Let's define the following function: :

In [ ]:
def f(x):
    return x**2 + 10*np.sin(x)

and plot it:

&gt;&gt;&gt; x = np.arange(-10, 10, 0.1) &gt;&gt;&gt; plt.plot(x, f(x))
\# doctest:+SKIP &gt;&gt;&gt; plt.show() \# doctest:+SKIP

This function has a global minimum around -1.3 and a local minimum
around 3.8.

Searching for minimum can be done with `scipy.optimize.minimize`, given
a starting point x0, it returns the location of the minimum that it has
found:

**result type**

The result of `scipy.optimize.minimize` is a compound object comprising
all information on the convergence

In [ ]:
result = sp.optimize.minimize(f, x0=0)
result # doctest: +ELLIPSIS

      fun: -7.9458233756...
 hess_inv: array([[0.0858...]])
      jac: array([-1.19209...e-06])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 5
     njev: 6
   status: 0
  success: True
        x: array([-1.30644...])

In [ ]:
result.x # The coordinate of the minimum  # doctest: +ELLIPSIS

array([-1.30644...])

**Methods**: As the function is a smooth function, gradient-descent
based methods are good options. The [lBFGS
algorithm](https://en.wikipedia.org/wiki/Limited-memory_BFGS) is a good
choice in general:

In [ ]:
sp.optimize.minimize(f, x0=0, method="L-BFGS-B")  # doctest: +ELLIPSIS

      fun: -7.94582338...
 hess_inv: <1x1 LbfgsInvHessProduct with dtype=float64>
      jac: array([-1.59872117e-06])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 12
      nit: 5
     njev: 6
   status: 0
  success: True
        x: array([-1.30644...])

Note how it cost only 12 functions evaluation above to find a good value
for the minimum.

**Global minimum**: A possible issue with this approach is that, if the
function has local minima, the algorithm may find these local minima
instead of the global minimum depending on the initial point x0:

In [ ]:
res = sp.optimize.minimize(f, x0=3, method="L-BFGS-B")
res.x

array([3.83746...])

If we don't know the neighborhood of the global minimum to choose the
initial point, we need to resort to costlier global optimization. To
find the global minimum, we use `scipy.optimize.basinhopping` (added in
version 0.12.0 of Scipy). It combines a local optimizer with sampling of
starting points:

In [ ]:
sp.optimize.basinhopping(f, 0)  # doctest: +SKIP

                  nfev: 1725
 minimization_failures: 0
                   fun: -7.9458233756152845
                     x: array([-1.30644001])
               message: ['requested number of basinhopping iterations completed successfully']
                  njev: 575
                   nit: 100

Note

`scipy` used to contain the routine $anneal$, it has been removed in
SciPy 0.16.0.

**Constraints**: We can constrain the variable to the interval `(0, 10)`
using the "bounds" argument:

**A list of bounds**

As `~scipy.optimize.minimize` works in general with x multidimensionsal,
the "bounds" argument is a list of bound on each dimension.

In [ ]:
res = sp.optimize.minimize(f, x0=1,
                        bounds=((0, 10), ))
res.x    # doctest: +ELLIPSIS

array([0.])

Tip

What has happened? Why are we finding 0, which is not a mimimum of our
function.

****Minimizing functions of several variables****

To minimize over several variables, the trick is to turn them into a
function of a multi-dimensional variable (a vector). See for instance
the exercise on 2D minimization below.

Note

`scipy.optimize.minimize_scalar` is a function with dedicated methods to
minimize functions of only one variable.

Finding minima of function is discussed in more details in the advanced
chapter: [mathematical\_optimization](mathematical_optimization.ipynb).

**Exercise: 2-D minimization**

[<img src="auto_examples/images/sphx_glr_plot_2d_minimization_002.png" alt="image" class="align-right" />](auto_examples/plot_2d_minimization.html)

The six-hump camelback function

$$f(x, y) = (4 - 2.1x^2 + \frac{x^4}{3})x^2 + xy + (4y^2 - 4)y^2$$

has multiple global and local minima. Find the global minima of this
function.

Hints:

> -   Variables can be restricted to $-2 < x < 2$ and $-1 < y < 1$.
> -   Use `numpy.meshgrid` and `matplotlib.pyplot.imshow` to find
>     visually the regions.
> -   Use `scipy.optimize.minimize`, optionally trying out several of
>     its methods.

How many global minima are there, and what is the function value at
those points? What happens for an initial guess of $(x, y) = (0, 0)$ ?

`solution <sphx_glr_intro_scipy_auto_examples_plot_2d_minimization.py>`

### Finding the roots of a scalar function

To find a root, i.e. a point where $f(x) = 0$, of the function $f$ above
we can use `scipy.optimize.root` :

In [ ]:
root = sp.optimize.root(f, x0=1)  # our initial guess is 1
root    # The full result

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 10
     qtf: array([1.33310463e-32])
       r: array([-10.])
  status: 1
 success: True
       x: array([0.])

In [ ]:
root.x  # Only the root found

array([0.])

Note that only one root is found. Inspecting the plot of $f$ reveals
that there is a second root around -2.5. We find the exact value of it
by adjusting our initial guess: :

In [ ]:
root2 = sp.optimize.root(f, x0=-2.5)
root2.x

array([-2.47948183])

Note

`scipy.optimize.root` also comes with a variety of algorithms, set via
the "method" argument.

[<img src="auto_examples/images/sphx_glr_plot_optimize_example2_001.png" alt="image" class="align-right" />](auto_examples/plot_optimize_example2.html)

Now that we have found the minima and roots of `f` and used curve
fitting on it, we put all those results together in a single plot:

<div style="clear: both"></div>

You can find all algorithms and functions with similar functionalities
in the documentation of `scipy.optimize`.

See the summary exercise on
[summary\_exercise\_optimize](summary_exercise_optimize.ipynb) for
another, more advanced example.

## Statistics and random numbers: `scipy.stats`

The module `scipy.stats` contains statistical tools and probabilistic
descriptions of random processes. Random number generators for various
random process can be found in `numpy.random`.

### Distributions: histogram and probability density function

Given observations of a random process, their histogram is an estimator
of the random process's PDF (probability density function): :

In [ ]:
samples = np.random.normal(size=1000)
bins = np.arange(-4, 5)
bins

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
histogram = np.histogram(samples, bins=bins, density=True)[0]
bins = 0.5*(bins[1:] + bins[:-1])
bins

array([-3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5])

In [ ]:
pdf = sp.stats.norm.pdf(bins)  # norm is a distribution object

In [ ]:
plt.plot(bins, histogram) # doctest: +ELLIPSIS

[<matplotlib.lines.Line2D object at ...>]

In [ ]:
plt.plot(bins, pdf) # doctest: +ELLIPSIS

[<matplotlib.lines.Line2D object at ...>]

[![image](auto_examples/images/sphx_glr_plot_normal_distribution_001.png)](auto_examples/plot_normal_distribution.html)

****The distribution objects****

`scipy.stats.norm` is a distribution object: each distribution in
`scipy.stats` is represented as an object. Here it's the normal
distribution, and it comes with a PDF, a CDF, and much more.

If we know that the random process belongs to a given family of random
processes, such as normal processes, we can do a maximum-likelihood fit
of the observations to estimate the parameters of the underlying
distribution. Here we fit a normal process to the observed data:

In [ ]:
loc, std = sp.stats.norm.fit(samples)
loc     # doctest: +ELLIPSIS

-0.045256707...

In [ ]:
std     # doctest: +ELLIPSIS

0.9870331586...

**Exercise: Probability distributions**

Generate 1000 random variates from a gamma distribution with a shape
parameter of 1, then plot a histogram from those samples. Can you plot
the pdf on top (it should match)?

Extra: the distributions have many useful methods. Explore them by
reading the docstring or by using tab completion. Can you recover the
shape parameter 1 by using the `fit` method on your random variates?

### Mean, median and percentiles

The mean is an estimator of the center of the distribution:

In [ ]:
np.mean(samples)     # doctest: +ELLIPSIS

-0.0452567074...

The median another estimator of the center. It is the value with half of
the observations below, and half above:

In [ ]:
np.median(samples)     # doctest: +ELLIPSIS

-0.0580280347...

Tip

Unlike the mean, the median is not sensitive to the tails of the
distribution. It is
["robust"](https://en.wikipedia.org/wiki/Robust_statistics).

**Exercise: Compare mean and median on samples of a Gamma distribution**

Which one seems to be the best estimator of the center for the Gamma
distribution?

The median is also the percentile 50, because 50% of the observation are
below it:

In [ ]:
sp.stats.scoreatpercentile(samples, 50)     # doctest: +ELLIPSIS

-0.0580280347...

Similarly, we can calculate the percentile 90:

In [ ]:
sp.stats.scoreatpercentile(samples, 90)     # doctest: +ELLIPSIS

1.2315935511...

Tip

The percentile is an estimator of the CDF: cumulative distribution
function.

### Statistical tests

[<img src="auto_examples/images/sphx_glr_plot_t_test_001.png" alt="image" class="align-right" />](auto_examples/plot_t_test.html)

A statistical test is a decision indicator. For instance, if we have two
sets of observations, that we assume are generated from Gaussian
processes, we can use a
[T-test](https://en.wikipedia.org/wiki/Student%27s_t-test) to decide
whether the means of two sets of observations are significantly
different:

In [ ]:
a = np.random.normal(0, 1, size=100)
b = np.random.normal(1, 1, size=10)
sp.stats.ttest_ind(a, b)   # doctest: +SKIP

(array(-3.177574054...), 0.0019370639...)

Tip

The resulting output is composed of:

-   The T statistic value: it is a number the sign of which is
    proportional to the difference between the two random processes and
    the magnitude is related to the significance of this difference.
-   the *p value*: the probability of both processes being identical. If
    it is close to 1, the two process are almost certainly identical.
    The closer it is to zero, the more likely it is that the processes
    have different means.

The chapter on [statistics](statistics.ipynb) introduces much more
elaborate tools for statistical testing and statistical data loading and
visualization outside of scipy.

## Numerical integration: `scipy.integrate`

### Function integrals

The most generic integration routine is `scipy.integrate.quad`. To
compute $\int_0^{\pi / 2} sin(t) dt$ :

In [ ]:
res, err = sp.integrate.quad(np.sin, 0, np.pi/2)
np.allclose(res, 1)   # res is the result, is should be close to 1

True

In [ ]:
np.allclose(err, 1 - res)  # err is an estimate of the err

True

Other integration schemes are available: `scipy.integrate.fixed_quad`,
`scipy.integrate.quadrature`, `scipy.integrate.romberg`...

### Integrating differential equations

`scipy.integrate` also features routines for integrating [Ordinary
Differential Equations
(ODE)](https://en.wikipedia.org/wiki/Ordinary_differential_equation). In
particular, `scipy.integrate.solve_ivp` solves ODE of the form:

In [ ]:
dy/dt = rhs(t, y)

Note

For a long time, the go-to method for solving an ODE was
`scipy.integrate.odeint`. The SciPy project recommends using
`scipy.integrate.solve_ivp` instead.

As an introduction, let us solve the ODE $\frac{dy}{dt} = -2 y$ between
$t = 0 \dots 4$, with the initial condition $y(t=0) = 1$. First the
function computing the derivative of the position needs to be defined:

In [ ]:
def calc_derivative(time, ypos):
    return -2 * ypos

[<img src="auto_examples/images/sphx_glr_plot_solve_ivp_simple_001.png" alt="image" class="align-right" />](auto_examples/plot_solve_ivp_simple.html)

Then, to compute `y` as a function of time:

In [ ]:
solution = sp.integrate.solve_ivp(calc_derivative, (0, 4), y0=(1,))

<div style="clear: both"></div>

Let us integrate a more complex ODE: a [damped spring-mass
oscillator](https://en.wikipedia.org/wiki/Harmonic_oscillator#Damped_harmonic_oscillator).
The position of a mass attached to a spring obeys the 2nd order *ODE*
$y'' + 2 \varepsilon \omega_0  y' + \omega_0^2 y = 0$ with
$\omega_0^2 = k/m$ with $k$ the spring constant, $m$ the mass and
$\varepsilon = c/(2 m \omega_0)$ with $c$ the damping coefficient. We
set:

In [ ]:
mass = 0.5  # kg
kspring = 4  # N/m
cviscous = 0.4  # N s/m

Hence:

In [ ]:
eps = cviscous / (2 * mass * np.sqrt(kspring/mass))
omega = np.sqrt(kspring / mass)

The system is underdamped, as:

In [ ]:
eps < 1

True

For `~scipy.integrate.solve_ivp`, the 2nd order equation needs to be
transformed in a system of two first-order equations for the vector
$Y = (y, y')$ : the function computes the velocity and acceleration:

In [ ]:
def calc_deri(time, yvec, eps, omega):
    return (yvec[1], -2.0 * eps * omega * yvec[1] - omega **2 * yvec[0])

[<img src="auto_examples/images/sphx_glr_plot_solve_ivp_damped_spring_mass_001.png" alt="image" class="align-right" />](auto_examples/plot_solve_ivp_damped_spring_mass.html)

Integration of the system follows:

In [ ]:
time_vec = np.linspace(0, 10, 100)
yinit = (1, 0)
solution = sp.integrate.solve_ivp(calc_deri, (0, 10), yinit, args=(eps, omega), method='LSODA')

<div style="clear: both"></div>

Tip

With the option $method='LSODA'$, `scipy.integrate.solve_ivp` uses the
LSODA (Livermore Solver for Ordinary Differential equations with
Automatic method switching for stiff and non-stiff problems), see the
[ODEPACK Fortran library]() for more details.

**Partial Differental Equations**

There is no Partial Differential Equations (PDE) solver in Scipy. Some
Python packages for solving PDE's are available, such as
[fipy](https://www.ctcms.nist.gov/fipy/) or
[SfePy](https://sfepy.org/doc/).

## Fast Fourier transforms: `scipy.fftpack`

The `scipy.fftpack` module computes fast Fourier transforms (FFTs) and
offers utilities to handle them. The main functions are:

-   `scipy.fftpack.fft` to compute the FFT
-   `scipy.fftpack.fftfreq` to generate the sampling frequencies
-   `scipy.fftpack.ifft` computes the inverse FFT, from frequency space
    to signal space

As an illustration, a (noisy) input signal (`sig`), and its FFT:

In [ ]:
sig_fft = sp.fftpack.fft(sig) # doctest:+SKIP
freqs = sp.fftpack.fftfreq(sig.size, d=time_step) # doctest:+SKIP

| [![signal\_fig](auto_examples/images/sphx_glr_plot_fftpack_001.png)](auto_examples/plot_fftpack.html) | [![fft\_fig](auto_examples/images/sphx_glr_plot_fftpack_002.png)](auto_examples/plot_fftpack.html) |
|-------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|
| **Signal**                                                                                            | **FFT**                                                                                            |

As the signal comes from a real function, the Fourier transform is
symmetric.

The peak signal frequency can be found with `freqs[power.argmax()]`

[<img src="auto_examples/images/sphx_glr_plot_fftpack_003.png" alt="image" class="align-right" />](auto_examples/plot_fftpack.html)

Setting the Fourrier component above this frequency to zero and
inverting the FFT with `scipy.fftpack.ifft`, gives a filtered signal.

Note

The code of this example can be found
`here <sphx_glr_intro_scipy_auto_examples_plot_fftpack.py>`

**$numpy.fft$**

Numpy also has an implementation of FFT (`numpy.fft`). However, the
scipy one should be preferred, as it uses more efficient underlying
implementations.

**Fully worked examples:**

| Crude periodicity finding (`link <sphx_glr_intro_scipy_auto_examples_solutions_plot_periodicity_finder.py>`)                                             | Gaussian image blur (`link <sphx_glr_intro_scipy_auto_examples_solutions_plot_image_blur.py>`)                                  |
|----------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
| [![periodicity\_finding](auto_examples/solutions/images/sphx_glr_plot_periodicity_finder_001.png)](auto_examples/solutions/plot_periodicity_finder.html) | [![image\_blur](auto_examples/solutions/images/sphx_glr_plot_image_blur_002.png)](auto_examples/solutions/plot_image_blur.html) |

**Exercise: Denoise moon landing image**

![image](../../data/moonlanding.png)

1.  Examine the provided image `moonlanding.png
    <../../data/moonlanding.png>`, which is heavily contaminated with
    periodic noise. In this exercise, we aim to clean up the noise using
    the Fast Fourier Transform.
2.  Load the image using `matplotlib.pyplot.imread`.
3.  Find and use the 2-D FFT function in `scipy.fftpack`, and plot the
    spectrum (Fourier transform of) the image. Do you have any trouble
    visualising the spectrum? If so, why?
4.  The spectrum consists of high and low frequency components. The
    noise is contained in the high-frequency part of the spectrum, so
    set some of those components to zero (use array slicing).
5.  Apply the inverse Fourier transform to see the resulting image.

`Solution <sphx_glr_intro_scipy_auto_examples_solutions_plot_fft_image_denoise.py>`

## Signal processing: `scipy.signal`

Tip

`scipy.signal` is for typical signal processing: 1D, regularly-sampled
signals.

[<img src="auto_examples/images/sphx_glr_plot_resample_001.png" alt="image" class="align-right" />](auto_examples/plot_resample.html)

**Resampling** `scipy.signal.resample` : resample a signal to $n$ points
using FFT. :

In [ ]:
t = np.linspace(0, 5, 100)
x = np.sin(t)

In [ ]:
x_resampled = sp.signal.resample(x, 25)

In [ ]:
plt.plot(t, x) # doctest: +ELLIPSIS

[<matplotlib.lines.Line2D object at ...>]

In [ ]:
plt.plot(t[::4], x_resampled, 'ko') # doctest: +ELLIPSIS

[<matplotlib.lines.Line2D object at ...>]

Tip

Notice how on the side of the window the resampling is less accurate and
has a rippling effect.

This resampling is different from the `interpolation
<intro_scipy_interpolate>` provided by `scipy.interpolate` as it only
applies to regularly sampled data.

[<img src="auto_examples/images/sphx_glr_plot_detrend_001.png" alt="image" class="align-right" />](auto_examples/plot_detrend.html)

**Detrending** `scipy.signal.detrend` : remove linear trend from signal:

In [ ]:
t = np.linspace(0, 5, 100)
x = t + np.random.normal(size=100)

In [ ]:
x_detrended = sp.signal.detrend(x)

In [ ]:
plt.plot(t, x) # doctest: +ELLIPSIS

[<matplotlib.lines.Line2D object at ...>]

In [ ]:
plt.plot(t, x_detrended) # doctest: +ELLIPSIS

[<matplotlib.lines.Line2D object at ...>]

<div style="clear: both"></div>

**Filtering**: For non-linear filtering, `scipy.signal` has filtering
(median filter `scipy.signal.medfilt`, Wiener `scipy.signal.wiener`),
but we will discuss this in the image section.

Tip

`scipy.signal` also has a full-blown set of tools for the design of
linear filter (finite and infinite response filters), but this is out of
the scope of this tutorial.

**Spectral analysis**: `scipy.signal.spectrogram` compute a spectrogram
--frequency spectrums over consecutive time windows--, while
`scipy.signal.welch` comptes a power spectrum density (PSD).

[![chirp\_fig](auto_examples/images/sphx_glr_plot_spectrogram_001.png)](auto_examples/plot_spectrogram.html)
[![spectrogram\_fig](auto_examples/images/sphx_glr_plot_spectrogram_002.png)](auto_examples/plot_spectrogram.html)
[![psd\_fig](auto_examples/images/sphx_glr_plot_spectrogram_003.png)](auto_examples/plot_spectrogram.html)

## Image manipulation: `scipy.ndimage`

orphan  

`scipy.ndimage` provides manipulation of n-dimensional arrays as images.

### Geometrical transformations on images

Changing orientation, resolution, .. :

In [ ]:
import scipy as sp

In [ ]:
# Load an image
face = sp.misc.face(gray=True)

In [ ]:
# Shift, roate and zoom it
shifted_face = sp.ndimage.shift(face, (50, 50))
shifted_face2 = sp.ndimage.shift(face, (50, 50), mode='nearest')
rotated_face = sp.ndimage.rotate(face, 30)
cropped_face = face[50:-50, 50:-50]
zoomed_face = sp.ndimage.zoom(face, 2)
zoomed_face.shape

(1536, 2048)

[<img src="/intro/scipy/auto_examples/images/sphx_glr_plot_image_transform_001.png" alt="image" class="align-center" />](auto_examples/plot_image_transform.html)

In [ ]:
plt.subplot(151)    # doctest: +ELLIPSIS

<AxesSubplot: >


In [ ]:
plt.imshow(shifted_face, cmap=plt.cm.gray)    # doctest: +ELLIPSIS

<matplotlib.image.AxesImage object at 0x...>


In [ ]:
plt.axis('off')

(-0.5, 1023.5, 767.5, -0.5)


In [ ]:
# etc.

### Image filtering

Generate a noisy face:

In [ ]:
import scipy as sp
face = sp.misc.face(gray=True)
face = face[:512, -512:]  # crop out square on right
import numpy as np
noisy_face = np.copy(face).astype(float)
noisy_face += face.std() * 0.5 * np.random.standard_normal(face.shape)

Apply a variety of filters on it:

In [ ]:
blurred_face = sp.ndimage.gaussian_filter(noisy_face, sigma=3)
median_face = sp.ndimage.median_filter(noisy_face, size=5)
wiener_face = sp.signal.wiener(noisy_face, (5, 5))

[<img src="/intro/scipy/auto_examples/images/sphx_glr_plot_image_filters_001.png" alt="image" class="align-center" />](auto_examples/plot_image_filters.html)

Other filters in `scipy.ndimage.filters` and `scipy.signal` can be
applied to images.

**Exercise**

Compare histograms for the different filtered images.

### Mathematical morphology

Tip

[Mathematical
morphology](https://en.wikipedia.org/wiki/Mathematical_morphology) stems
from set theory. It characterizes and transforms geometrical structures.
Binary (black and white) images, in particular, can be transformed using
this theory: the sets to be transformed are the sets of neighboring
non-zero-valued pixels. The theory was also extended to gray-valued
images.

<img src="/intro/scipy/image_processing/morpho_mat.png" alt="image" class="align-center" />

Mathematical-morphology operations use a *structuring element* in order
to modify geometrical structures.

Let us first generate a structuring element:

In [ ]:
el = sp.ndimage.generate_binary_structure(2, 1)
el # doctest: +NORMALIZE_WHITESPACE +ELLIPSIS

array([[False, True, False],
       [...True, True, True],
       [False, True, False]])

In [ ]:
el.astype(int)

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 0]])

-   **Erosion** `scipy.ndimage.binary_erosion` :

In [ ]:
    a = np.zeros((7, 7), dtype=int)
    a[1:6, 2:5] = 1
    a

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
    sp.ndimage.binary_erosion(a).astype(a.dtype)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
    # Erosion removes objects smaller than the structure
    sp.ndimage.binary_erosion(a, structure=np.ones((5,5))).astype(a.dtype)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

-   **Dilation** `scipy.ndimage.binary_dilation` :

In [ ]:
    a = np.zeros((5, 5))
    a[2, 2] = 1
    a

array([[0.,  0.,  0.,  0.,  0.],
       [0.,  0.,  0.,  0.,  0.],
       [0.,  0.,  1.,  0.,  0.],
       [0.,  0.,  0.,  0.,  0.],
       [0.,  0.,  0.,  0.,  0.]])

In [ ]:
    sp.ndimage.binary_dilation(a).astype(a.dtype)

array([[0.,  0.,  0.,  0.,  0.],
       [0.,  0.,  1.,  0.,  0.],
       [0.,  1.,  1.,  1.,  0.],
       [0.,  0.,  1.,  0.,  0.],
       [0.,  0.,  0.,  0.,  0.]])

-   **Opening** `scipy.ndimage.binary_opening` :

In [ ]:
    a = np.zeros((5, 5), dtype=int)
    a[1:4, 1:4] = 1
    a[4, 4] = 1
    a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
    # Opening removes small objects
    sp.ndimage.binary_opening(a, structure=np.ones((3, 3))).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
    # Opening can also smooth corners
    sp.ndimage.binary_opening(a).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

-   **Closing:** `scipy.ndimage.binary_closing`

**Exercise**

Check that opening amounts to eroding, then dilating.

An opening operation removes small structures, while a closing operation
fills small holes. Such operations can therefore be used to "clean" an
image. :

In [ ]:
a = np.zeros((50, 50))
a[10:-10, 10:-10] = 1
a += 0.25 * np.random.standard_normal(a.shape)
mask = a>=0.5
opened_mask = sp.ndimage.binary_opening(mask)
closed_mask = sp.ndimage.binary_closing(opened_mask)

[<img src="/intro/scipy/auto_examples/images/sphx_glr_plot_mathematical_morpho_001.png" alt="image" class="align-center" />](auto_examples/plot_mathematical_morpho.html)

**Exercise**

Check that the area of the reconstructed square is smaller than the area
of the initial square. (The opposite would occur if the closing step was
performed *before* the opening).

For *gray-valued* images, eroding (resp. dilating) amounts to replacing
a pixel by the minimal (resp. maximal) value among pixels covered by the
structuring element centered on the pixel of interest. :

In [ ]:
a = np.zeros((7, 7), dtype=int)
a[1:6, 1:6] = 3
a[4, 4] = 2; a[2, 3] = 1
a

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 1, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 2, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
sp.ndimage.grey_erosion(a, size=(3, 3))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 3, 2, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

### Connected components and measurements on images

Let us first generate a nice synthetic binary image. :

In [ ]:
x, y = np.indices((100, 100))
sig = np.sin(2*np.pi*x/50.) * np.sin(2*np.pi*y/50.) * (1+x*y/50.**2)**2
mask = sig > 1

[<img src="/intro/scipy/auto_examples/images/sphx_glr_plot_connect_measurements_001.png" alt="image" class="align-center" />](auto_examples/plot_connect_measurements.html)

[<img src="/intro/scipy/auto_examples/images/sphx_glr_plot_connect_measurements_002.png" alt="image" class="align-right" />](auto_examples/plot_connect_measurements.html)

`scipy.ndimage.label` assigns a different label to each connected
component:

In [ ]:
labels, nb = sp.ndimage.label(mask)
nb

8

<div style="clear: both"></div>

Now compute measurements on each connected component:

In [ ]:
areas = sp.ndimage.sum(mask, labels, range(1, labels.max()+1))
areas   # The number of pixels in each connected component

array([190.,   45.,  424.,  278.,  459.,  190.,  549.,  424.])

In [ ]:
maxima = sp.ndimage.maximum(sig, labels, range(1, labels.max()+1))
maxima  # The maximum signal in each connected component

array([ 1.80238238,   1.13527605,   5.51954079,   2.49611818, 6.71673619,
        1.80238238,  16.76547217,   5.51954079])

[<img src="/intro/scipy/auto_examples/images/sphx_glr_plot_connect_measurements_003.png" alt="image" class="align-right" />](auto_examples/plot_connect_measurements.html)

Extract the 4th connected component, and crop the array around it:

In [ ]:
sp.ndimage.find_objects(labels==4) # doctest: +SKIP

[(slice(30L, 48L, None), slice(30L, 48L, None))]

In [ ]:
sl = sp.ndimage.find_objects(labels==4)
import matplotlib.pyplot as plt
plt.imshow(sig[sl[0]])   # doctest: +ELLIPSIS

<matplotlib.image.AxesImage object at ...>

See the summary exercise on `summary_exercise_image_processing` for a
more advanced example.

## Summary exercises on scientific computing

The summary exercises use mainly Numpy, Scipy and Matplotlib. They
provide some real-life examples of scientific computing with Python. Now
that the basics of working with Numpy and Scipy have been introduced,
the interested user is invited to try these exercises.

latex

summary-exercises/stats-interpolate.rst
summary-exercises/optimize-fit.rst
summary-exercises/image-processing.rst
summary-exercises/answers\_image\_processing.rst

html

**Exercises:**

summary-exercises/stats-interpolate.rst
summary-exercises/optimize-fit.rst
summary-exercises/image-processing.rst

**Proposed solutions:**

summary-exercises/answers\_image\_processing.rst

**References to go further**

-   Some chapters of the [advanced](advanced_topics_part) and the
    [packages and applications](applications_part) parts of the scipy
    lectures
-   The [scipy cookbook](https://scipy-cookbook.readthedocs.io)